language: php

php:
  - 5.5
  - 5.6
  - '7'

install:
  - composer self-update

before_script:
  - cp .env.travis .env
  - cp travis.phpunit.xml phpunit.xml
  - mkdir /tmp/timegrid
  - mysql -e 'create database test_timegrid;'
  - composer install --dev --no-interaction
  - php artisan key:generate
  - php artisan migrate
  - php artisan db:seed
  - php artisan geoip:update

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/test-reporter
