language: php

php:
  - "5.6"
  - "7.1"

services:
  - mysql

before_install:
  - sudo apt-get update

install:
  - composer self-update

before_script:
  - mv .env.travis .env
  - mv travis.phpunit.xml phpunit.xml
  - mysql -e 'create database test_timegrid;'
  - composer install --dev --no-interaction
  - php artisan config:clear
  - php artisan migrate
  - php artisan db:seed
#  - php artisan geoip:update
  - php artisan config:cache

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - ./travis-codeclimate-report.sh
